[dist]
  # Directory where the dist output is located
  publish = "dist"

  # Command to build your site
  command = "npm run build"

[[redirects]]
  # Redirect all requests to the index.html file (useful for single-page apps)
  from = "/*"
  to = "/index.html"
  status = 200
